---
include:
#  - board: nice_nano_v2
#    shield: eyeslash_corne_central_dongle prospector_adapter
#    snippet: studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
#     artifact-name: eyeslash_corne_central_dongle
  - board: seeeduino_xiao_ble
    shield: eyeslash_corne_central_dongle rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: xiao_dongle
  - board: nice_nano_v2
    shield: eyeslash_corne_peripheral_left nice_view_custom
  - board: nice_nano_v2
    shield: eyeslash_corne_peripheral_right nice_view_custom
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao_reset_settings
